# Generated by Django 5.2.3 on 2025-07-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shoe_created_at_shoe_in_stock_alter_shoe_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('Sneakers', 'Sneakers'), ('Boots', 'Boots'), ('Sandals', 'Sandals'), ('Loafers', 'Loafers'), ('Formal', 'Formal')], default='Sneakers', max_length=20),
        ),
        migrations.AddField(
            model_name='shoe',
            name='sizes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
