# Generated by Django 5.2.3 on 2025-07-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shoe_category_shoe_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='section',
            field=models.CharField(choices=[('Men', 'Men'), ('Ladies', 'Ladies'), ('Kids', 'Kids'), ('Heels', 'Heels')], default='Men', max_length=20),
        ),
    ]
