# Generated by Django 5.2.3 on 2025-07-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_shoe_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='section',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('Sneakers', 'Sneakers'), ('Boots', 'Boots'), ('Sandals', 'Sandals'), ('Loafers', 'Loafers'), ('Formal', 'Formal'), ('Heels', 'Heels')], default='Sneakers', max_length=20),
        ),
    ]
