# Generated by Django 5.2.3 on 2025-07-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_shoe_section_alter_shoe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='section',
            field=models.CharField(choices=[('Men', 'Men'), ('Ladies', 'Ladies'), ('Kids', 'Kids')], default='Men', max_length=20),
        ),
    ]
